version: "3.8"
services:
  WMPHS:
    container_name: WMPHS
    image: s20683/wmphs:latest
    pull_policy: always
    ports:
      - "9090:9090"
    depends_on:
      - postgres-wmphs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-wmphs:5432/WMPHS
      SPRING_DATASOURCE_USERNAME: s20683
      SPRING_DATASOURCE_PASSWORD: s20683
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - s20683-psql
#    volumes:
#      - ./web-static:/web-static


  postgres-wmphs:
    container_name: postgres-wmphs
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: WMPHS
      POSTGRES_USER: s20683
      POSTGRES_PASSWORD: s20683
    ports:
      - "5432:5432"
    restart: always
    networks:
      - s20683-psql
volumes:
  postgres-data:

networks:
  s20683-psql:
    driver: bridge
